### PR TITLE
Fixes to run sugar-high on 1.8.7 machines. 

### PR DESCRIPTION
**Pull request by stanislaw**
Go travis!

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Thanks a lot Stan! I know, Travis rules... just takes a little extra effort ;)

**Comment by stanislaw** [comment]
Kris, please also release a gem with this.

**Comment by kristianmandrup** [comment]
okay ;)

**Comment by kristianmandrup** [comment]
Note that I extracted the Rails concern code into a new "concerned" gem. Works beautifully with ActiveSupport::Concern pattern :)

**Comment by kristianmandrup** [comment]
Pushing gem to https://rubygems.org...
Successfully registered gem: sugar-high (0.7.0)

**Comment by stanislaw** [comment]
Thanks!

**Pull request merged**
